# Image for Hashicorp's Terraform. It currently uses the same terraform-work image that TFE utilizes.
  image:
    name: registry.gitlab.com/rpt-ops/terraformofficehours:1.0
  
  cache:
    paths:
      - .terraform
  
  before_script:
    - terraform --version
    - terraform init
  
  stages:
    - validate
  
  # Validate section.
  validate:validate:
    stage: validate
    script:
      - terraform validate
    only:
      - branches
      - merge_requests
    tags:
      - linux
      - terraform
  
  validate:format:
    stage: validate
    script:
      - terraform fmt
      - terraform fmt -write=false -diff
    only:
      - branches
      - merge_requests
    tags:
      - linux
      - terraform